/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VidangesRouteImport } from './routes/vidanges'
import { Route as VehiculeRouteImport } from './routes/vehicule'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntretienRouteImport } from './routes/entretien'
import { Route as AssuranceRouteImport } from './routes/assurance'
import { Route as IndexRouteImport } from './routes/index'

const VidangesRoute = VidangesRouteImport.update({
  id: '/vidanges',
  path: '/vidanges',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculeRoute = VehiculeRouteImport.update({
  id: '/vehicule',
  path: '/vehicule',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretienRoute = EntretienRouteImport.update({
  id: '/entretien',
  path: '/entretien',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceRoute = AssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/entretien': typeof EntretienRoute
  '/login': typeof LoginRoute
  '/scanner': typeof ScannerRoute
  '/vehicule': typeof VehiculeRoute
  '/vidanges': typeof VidangesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/entretien': typeof EntretienRoute
  '/login': typeof LoginRoute
  '/scanner': typeof ScannerRoute
  '/vehicule': typeof VehiculeRoute
  '/vidanges': typeof VidangesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/entretien': typeof EntretienRoute
  '/login': typeof LoginRoute
  '/scanner': typeof ScannerRoute
  '/vehicule': typeof VehiculeRoute
  '/vidanges': typeof VidangesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assurance'
    | '/entretien'
    | '/login'
    | '/scanner'
    | '/vehicule'
    | '/vidanges'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assurance'
    | '/entretien'
    | '/login'
    | '/scanner'
    | '/vehicule'
    | '/vidanges'
  id:
    | '__root__'
    | '/'
    | '/assurance'
    | '/entretien'
    | '/login'
    | '/scanner'
    | '/vehicule'
    | '/vidanges'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssuranceRoute: typeof AssuranceRoute
  EntretienRoute: typeof EntretienRoute
  LoginRoute: typeof LoginRoute
  ScannerRoute: typeof ScannerRoute
  VehiculeRoute: typeof VehiculeRoute
  VidangesRoute: typeof VidangesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vidanges': {
      id: '/vidanges'
      path: '/vidanges'
      fullPath: '/vidanges'
      preLoaderRoute: typeof VidangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicule': {
      id: '/vehicule'
      path: '/vehicule'
      fullPath: '/vehicule'
      preLoaderRoute: typeof VehiculeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretien': {
      id: '/entretien'
      path: '/entretien'
      fullPath: '/entretien'
      preLoaderRoute: typeof EntretienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance': {
      id: '/assurance'
      path: '/assurance'
      fullPath: '/assurance'
      preLoaderRoute: typeof AssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssuranceRoute: AssuranceRoute,
  EntretienRoute: EntretienRoute,
  LoginRoute: LoginRoute,
  ScannerRoute: ScannerRoute,
  VehiculeRoute: VehiculeRoute,
  VidangesRoute: VidangesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
